spring.application.name=tierforge-backend
server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5433/tierforge
spring.datasource.username=tierforge
spring.datasource.password=tierforge

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
